---
  - name: supervisor | main.yml | install supervisor
    pip: name={{ supervisor.package }} version={{ supervisor.version }}

  - name: supervisor | main.yml | ensure supervisor directory
    file: state=directory path=/etc/supervisor owner=root group=root

  - name: supervisor | main.yml | ensure supervisor conf.d directory
    file: state=directory path=/etc/supervisor/conf.d owner=root group=root

  - name: supervisor | main.yml | ensure supervisor configuration
    template: src={{ supervisor.conf.path }} dest=/etc/supervisor/supervisord.conf group=root owner=root

  - name: supervisor | main.yml | enable supervisor apps
    template: src={{ item.src_path }} dest=/etc/supervisor/conf.d/{{ item.target_name }} group=root owner=root
    with_items: supervisor.apps_conf
    when: supervisor.apps_conf is defined and not((supervisor.apps_conf is none) or (supervisor.apps_conf|trim == ''))
