---
  - name: uwsgi | main.yml | ensure uwsgi dependencies installed
    apt: name={{ item }} update_cache=yes cache_valid_time=3600
    with_items:
      - build-essential
      - python
      - python-dev
      - python-pip

  - name: uwsgi | main.yml | install uwsgi
    pip: name={{ uwsgi.package }} version={{ uwsgi.version }}

  - name: uwsgi | main.yml | ensure uwsgi directories
    file: path={{ item }} state=directory group=root owner=root
    with_items:
      - '/etc/uwsgi/apps-available'
      - '/etc/uwsgi/apps-enabled'

  - name: uwsgi | main.yml | ensure uwsgi configuration
    template: src={{ item.src_path }} dest=/etc/uwsgi/apps-available/{{ item.target_name }} group=root owner=root
    with_items: uwsgi.apps_conf
    when: uwsgi.apps_conf is defined and not((uwsgi.apps_conf is none) or (uwsgi.apps_conf|trim == ''))

  - name: uwsgi | main.yml | enable uwsgi in sites-enabled
    file: src=/etc/uwsgi/apps-available/{{ item.target_name }} path=/etc/uwsgi/apps-enabled/{{ item.target_name }} state=link group=root owner=root
    with_items: uwsgi.apps_conf
    when: uwsgi.apps_conf is defined and not((uwsgi.apps_conf is none) or (uwsgi.apps_conf|trim == ''))
