---
  - hosts: web
    sudo: yes
    roles:
      - web

  - include: deploy.yml

  - hosts: web
    sudo: yes
    tasks:
      - name: site | site.yml | restart application
        supervisorctl: name={{ deploy.supervisor.group }} state=restarted config=/etc/supervisor/supervisord.conf
        when: deploy.supervisor.group is defined and not((deploy.supervisor.group is none) or (deploy.supervisor.group|trim == ''))
