---
  - name: nginx | remove-defaults.yml | remove default site
    file: path=/etc/nginx/sites-enabled/default state=absent
    sudo: yes
    notify:
      - reload nginx

  - name: nginx | remove-defaults.yml | remove default configuration
    file: path=/etc/nginx/conf.d/{{ item }} state=absent
    sudo: yes
    with_items:
      - default.conf
      - example_ssl.conf
    notify:
      - reload nginx
